### ISSUE TITLE
REI and Crafting Table Support Feature Request Reminder (As well as enchantment table suggestion]

### ISSUE THREAD

**Issue by NealSavage** [AHilyard/EquipmentCompare#6]
As you requested, here is the reminder to add REI compatibility, as well as the ability to compare equipment within the crafting table. 

I also just thought of perhaps at the enchanting table, when ingredients are placed and it is showing an enchanted item to take from the table, one could be able to compare the stats of the enchanted item against the item's stats pre-enchantment. This would helpful in deciding if applying an enchantment is worth it.

**Comment by AHilyard** [comment]
Sorry for the delay on this, I have added support for REI and the crafting table in version 1.3.0. 
I considered your suggestion for the enchanting table but decided not to go with it because of the random nature of enchanting table results--in practice it can be confusing when you see a tooltip but then get different results afterword.  If it's any consolation, I did also add support for comparisons from anvils for before/after enchantment comparisons, since it doesn't suffer from the same problem.
